Automattic/wpcom.js

- lib/post.js
When a post is added the `_id`and `_slug` are propagated.
> post: propagate `id` and `slug` when post is added

- lib/site.js
- test/test.wpcom.site.js
In #89 I failed to add a test for the `site.statsVideo` method, and ironically there was a bug with that method.  I have fixed the error and added a test to cover this endpoint as well.
> Fix site.statsVideo

- lib/category.js
- lib/comment.js
- lib/commentlike.js
- lib/follow.js
- lib/like.js
- lib/post.js
- lib/reblog.js
- lib/site.js
- lib/tag.js
For Team I/O's current meetup project we're beefing up the developer site, including generating sample API requests.  I'm doing some static+runtime analysis of wpcom.js to auto-generate the code for these requests.  These are jsdoc and other changes needed to support that work.
> Fix jsdoc etc. to support static+runtime analysis

- lib/comment.js
- lib/commentlike.js
- lib/follow.js
- lib/like.js
- lib/post.js
- lib/reblog.js
- lib/util/request.js
There is no change in behavior due to this commit, but it will have a
few benefits for auto-generated code samples:
- Show `.del()` instead of `.delete()` (to avoid potential problems with
`delete` keyword)
- Show `.mine()` instead of `.state()` (since the endpoints are named
with `/mine` in the path)
- Show `.post()` instead of `.put()` (if one day we do examples for
the `this.wpcom.req` methods)
> Rearrange alias order

- docs/site.md
- lib/site.js
The current `statsPostViews` and `statsVideo` methods don't allow for passing in additional query options.  This PR adds in the query option as an optional attribute.  This would allow one call to `statsPostViews` on calypso to not use an undocumented implementation.
> Site: Allow Query Options on statsVideo and statsPostViews

- docs/comment.md
- docs/follow.md
- docs/like.md
- docs/post.md
- docs/reblog.md
A number of the docs pages use this syntax:
`wpcom.sites('blog.wordpress.com')`
...but attempting to use this results in <code>Uncaught TypeError: wpcom.sites is not a function</code>.
Looking at the tests and the [docs for the site handler itself](https://github.com/Automattic/wpcom.js/blob/master/docs/site.md), it looks like the syntax should actually be:
`wpcom.site('blog.wordpress.com')`
I've changed all instances of this in the docs.
> Docs: change wpcom.sites() to wpcom.site()

- lib/batch.js
- lib/util/send-request.js
- package.json
The wpcom API expects batched requests to be of the form:
`urls[]=/first&urls[]=/second`
The current wpcom.js is sending it as:
`urls[]=/first,/second`
When the current wpcom.js is sending this over `wpcom-proxy-request` the problem disappears as `wpcom-proxy-request` uses `jQuery.param()` to convert the parameters, and this encodes them in PHP-style. When sent with `wpcom-xhr-request` it doesn't get converted
This PR manually encodes the query string and passes it to send-request as a string rather than an object. It fixes `wpcom-xhr-request` and doesn't seem to have any effect on `wpcom-proxy-request`.
I'm unaware of the greater context of this change so feel free to modify as needed.
Added:
I think this is related to this:
https://github.com/visionmedia/superagent/issues/670
The …
> Use PHP style query params for a batch request

- lib/site.js
- test/test.wpcom.site.js
Hey @retrofox, this adds a newly-documented endpoint to retrieve all possible `page-templates` for a given site. `page-templates` are dictated by the active theme for a site. Not all themes will have `page-templates` available, but then it should return an empty array.
> adds the page templates endpoint and test

- Makefile
Previously, if you ran the following sequence it failed:
```bash
make clean
make test-all
```
This patch adjusts the `Makefile` to build the node modules if they don't exist when running the tests.
> Make tests depend on node_modules

- Makefile
- lib/batch.js
- lib/comment.js
- lib/media.js
- lib/post.js
- lib/reblog.js
- lib/util/request.js
- lib/util/send-request.js
- test/test.apiVersion.js
- test/test.util.req.js
- test/test.wpcom.batch.js
- test/test.wpcom.js
- test/test.wpcom.me.js
- test/test.wpcom.site.category.js
- test/test.wpcom.site.embeds.js
- test/test.wpcom.site.follow.js
- test/test.wpcom.site.js
- test/test.wpcom.site.media.js
- test/test.wpcom.site.post.comment.js
- test/test.wpcom.site.post.js
- test/test.wpcom.site.post.like.js
- test/test.wpcom.site.post.reblog.js
- test/test.wpcom.site.shortcodes.js
- test/test.wpcom.site.tag.js
- test/test.wpcom.users.js
- test/util.js
Contrast to the wrapper approach in #112. This introduces Promises in a much smoother and less obtuse way.
Previously, if no callback were passed into the wpcom requests, a
default callback that threw an exception on error was introduced and
executed.
Now, however, we can use the absence of a callback to indicate that we
would prefer to have a promise returned that rejects or resolves
corresponding to the API response.
This requires support for promises, however, meaning that `wpcom.js`
will need to be built inside of a project that transpiles or polyfills.
> Set default Promise return in absence of callback

- index.js
- test/test.wpcom.promises.js
This isn't needed since promises are built-in by default now. It was put
in place as a hold-off until a final solution could be found, and the
default promises are working great.
> Removes the Promise wrapper

- .eslintrc
- index.js
- lib/batch.js
- lib/category.js
- lib/comment.js
- lib/commentlike.js
- lib/follow.js
- lib/like.js
- lib/me.js
- lib/media.js
- lib/post.js
- lib/reblog.js
- lib/site.js
- lib/tag.js
- lib/users.js
- lib/util/request.js
- lib/util/send-request.js
- package.json
I generated this config based on the existing library coding style. It
formalizes patterns in use but doesn't attempt to change them.
In cases where multiple styles were present, the pattern most-used was
selected. Usually there were no close-calls.
> Formalize the coding style already in use

- lib/media.js
- test/fixture.json
When giving an object (or a list containing an object) to `Media#addUrls`, the url may not be retrieved properly if the `url` key is not the last entry in the object.
This was not detected earlier probably because we usually give url strings to this function, but giving an object is useful to define other attributes (such as the `parent_id`/`post_ID`) for this media.
Related issue https://github.com/Automattic/wpcom.js/issues/119
> Fix typo in Media#addUrls

- docs/me.md
- lib/me.js
- test/test.wpcom.me.js
The `me/connections` endpoint has been deprecated and removed from WordPress.com's REST API. It was never a documented endpoint, so its removal does not affect any production clients. 
The endpoints are replaced by equivalent (but still undocumented for now) v1.1 endpoints. Once documented, I believe we can add them to wpcom.js.
Note: I wasn't sure if I should also apply the removal to `/dist` or if there is some automated process that takes care of that for us.
Pinging @aduth for a review.
> Remove deprecated `me/connections` endpoint

- package.json
While working on my wcus talk with the example app [here](https://github.com/timmyc/doggfood), the new promises logic broke my build since `babel-runtime` is not an explicit dependency in this package.  I believe everything is working fine in wp-calypso with the current build because that package is required explicitly by that project.
I was able to fix my example app by adding the dependency too, but we should fix it here as well.
/cc @retrofox
> Move babel-runtime to dependencies

- lib/util/send-request.js
Adding in some more logic to support the upcoming adoption of WP-API on WordPress.com.  In lieu of keying off of `apiVersion` we are opting to add in a new "special" param for `apiNamespace`.  The WP-API uses namespaces to group logic - for example the default namespace is `wp/2` - and probably down the road as we migrate existing wpcom endpoints to WP-API we will use `wpcom/2.0`.
Our initial hope was to treat any `apiVersion` >= 2.0 as a WP-API request, but as we vetted this out further, we realized that approach might cause issues in the future.  Case in point - there is an `oembed/1.0` namespace and version combo right now that would not work with using apiVersion >= 2.0 logic.
With this logic in place we can sniff for `apiNamespace` in the rest-proxy and `wpcom-xhr-request` and adjust …
> WP-API: Add support for apiNamespace

- History.md
- package.json
Version bump to get `apiNamespace` available for use.
/cc @retrofox
> Release 4.8.4

- lib/runtime/site.get.json
- lib/site.domain.js
- lib/site.js
- test/test.wpcom.site.domain.js
- test/test.wpcom.site.js
Add site domain methods
```es6
import wpcomFactory from 'wpcom';
const wpcom = wpcomFactory();
const site = wpcom.site( '<your-testing-blog>' );
// get domains list for the site
site.domainsList().then( list => {
console.log( 'domains list %o', list );
} );
// create domains handler
const domain = site.domain();
// get primary domain for the website
domain.getPrimary().then( data => {
// data response
} );
```
> Add `site.domain`

- dist/lib/site.post.js
- lib/site.post.js
- test/test.wpcom.site.js
- test/test.wpcom.site.post.js
- test/util.js
The `post.del()` method was removed [here](https://github.com/Automattic/wpcom.js/commit/62c8b0350d9c1e1adfcc3ba9ca17273fbdd6da37#diff-e8f27921d011a8bda23fc19c8ef33536) which resulted in some breakage in wp-calypso.  This branch adds the method back in, along with a test for it.
There is also some test suite fixes that I had originally submitted in #157.  Specifically, the change to the test utils will respect a site.ID if set in `lib/test/config.json` or a `SITE` passed in as an ENV variable.  Additionally the `postCounts` tests are fixed up to work on test sites that have no posts.
__To Test__
- `make test site.post.del`
- `make test site.postCounts`
> Add back post.del() and some test updates.

- lib/site.plugin.js
The update() method is know to be used to update data of the entity that we are working on. For instance we can update a Post using `Post#update()`, or an image `using Media#update()` and so on.
For this reason I've changed the method name used to update the plugin to the last stable version with the `updateVersion` name and keep the `update` method used to update the plugin configuration.
> SitePlugin: rename methods to be consistent.

- dist/lib/site.js
- dist/lib/site.post-type.js
- lib/site.js
- lib/site.post-type.js
- test/test.wpcom.site.post-type.js
This pull request seeks to add support for the `GET /sites/%s/post-types/%s/taxonomies` endpoint, accessible in wpcom.js via `wpcom.site( siteId ).postType( postType ).taxonomiesList()`.
> Enable support for post types taxonomies endpoint

- lib/site.ad-credit-vouchers.js
- lib/site.js
Add SiteAdCreditVouchers class to handle site vouchers endpoints.
Creates a new SiteAdCreditVouchers instance
```es6
const site = wpcom.site( 'mitestingblog.wordpress.com' );
const vouchers = site.vouchers();
```
Get the whole vouchers list
```es6
wpcom
.site( 'mitestingblog.wordpress.com' )
.vouchers()
.list()
.then( list => console.log( list ); )
.catch( err => console.error( err ); )
```
Get vouchers list by service type
```es6
wpcom
.site( 'mitestingblog.wordpress.com' )
.vouchers()
.get( 'google-ad-credits' )
.then( list => console.log( list ); )
.catch( err => console.error( err ); )
```
Assign a voucher by service type
```es6
wpcom
.site( 'testing.wordpress.com' )
.adCreditVouchers()
.assign( 'google-ad-credits' )
.then( data => console.log( data ) )
.catch( error => console.error( …
```
> SiteAdCreditVouchers: first implementation

- index.js
- lib/marketing.js
- lib/marketing.survey.js
Add code to that allows us handle marketing surveys through of the `/marketing/survey` endpoint.
Creates a `Marketing` instance
Creates a `MarketingSurvey` instance with the given survey `id` and `siteId` (optional).
Set site id to be used when a survey is submitted.
Add a par `key`-`value` to the survey responses.
Add an object of responses to survey.
Submit the marketing survey
```es6
import wpcom from 'wpcom';
var survey = wpcom.marketing().survey( 'best-cartoons', 9073334 );
// add a response to the survey
surver.addResponse( 'adventure-time', 'Adventure Time' );
// Add other responses
survay.addResponses( {
'gumball': 'The Amazing World of Gumball',
'gravity-falls': 'Gravity Falls'
} );
// Finally send the survey
survey.submit()
.then( resp => console.log( respo ) )
.catch( err => …
```
> Add marketing survey stuff

- lib/site.credit-vouchers.js
- lib/site.js
In order to remove `ad` from the stuff I decided rename methods, files, etc.
cc @rralian
> rename `ad-credit-vouchers` to `credit-voucher`

- index.js
- lib/me.connected-application.js
- lib/me.js
- lib/me.keyring-connection.js
- lib/me.publicize-connection.js
- lib/me.settings.js
- lib/me.settings.password.js
- lib/me.settings.profile-links.js
- lib/me.two-step.js
- lib/me.two-step.sms.js
- lib/site.category.js
- lib/site.comment.js
- lib/site.comment.like.js
- lib/site.follow.js
- lib/site.media.js
- lib/site.post.like.js
- lib/site.post.reblog.js
- lib/site.tag.js
- lib/site.wordads.earnings.js
- lib/site.wordads.js
- lib/site.wordads.settings.js
- lib/site.wordads.tos.js
- lib/users.js
- lib/util/pinghub.js
- lib/util/request.js
- lib/util/send-request.js
- package.json
`n8-make` v1.3.0 adds the ["add-module-exports"](https://www.npmjs.com/package/babel-plugin-add-module-exports) babel plugin by default,
which allows us to use proper ES6 `export` syntax and
have it properly work with the Node.js module system still.
> Use ES6 `export` keyword consistently

- Makefile
- lib/me.settings.js
- lib/site.comment.js
- lib/site.media.js
- lib/site.wordads.earnings.js
- lib/site.wordads.js
- lib/site.wordads.settings.js
- lib/site.wordads.tos.js
- lib/util/pinghub.js
- lib/util/request.js
- lib/util/send-request.js
- package.json
- test/util.js
- webpack.config.js
Use `ROOT` env var to set sources files to compile. Also I've added `compile` rule to set 8 parallel process in the building process.
```make
compile:
make build --jobs=8
```
I've restored the `standalone` make rule as well. 
Let's publish only the useful files in the npm package:
- index.js
- README.md
- History.md
- lib/
The tests files aren't compiled anymore.
To support ES6 with mocha I've added `babel-register` with its presets and thus add the js compilers to mocha command through of `--compilers` parameter.
> Improve compiling process

- Makefile
- circle.yml
- test/test.apiVersion.js
- test/test.wpcom.batch.js
- test/test.wpcom.site.settings.js
In this PR I've changed slightly the tests rules:
```bash
> make test
```
```bash
> FILTER=wpcom.site.settings make test-watch
```
**screenshot**
**video**
https://cloudup.com/csmrGGDNHpB
> remove `test-all` and add `make-watch` rule

- index.js
For example, so that we can get access to the `Me` constructor
via `import { Me } from 'wpcom'` instead of the current
way of `import Me from 'wpcom/build/lib/me'` which relies on
the implementation details of the `build` and `lib` dirs.
> re-export the Classes

- README.md
This PR fixes a typo found in 4 places in README.md
> Fix type: then() and catch() in README.md should be preceded by period.

- lib/util/send-request.js
All request handlers used by wpcom.js in calypso ([wpcom-proxy-request](https://github.com/Automattic/wpcom-proxy-request/blob/master/index.js#L144) and [wpcom-xhr-request](https://github.com/Automattic/wpcom-xhr-request/blob/master/index.js#L78)) send a third parameter in their callback: headers.
This PR adds support for that third parameter. This can be used to get access to the [pagination headers](https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/) used by the REST API: `X-WP-Total` and `X-WP-TotalPages`
I didn't update the promise version as it's not needed to [unblock my use case](https://github.com/Automattic/wp-calypso/pull/13828) and would introduce considerable changes (most likely an envelope containing both the headers and the results)
The calypso test …
> Send Request: Forward response headers with the response results

- package.json
https://github.com/Automattic/wp-calypso/pull/23259 was no problem. Even though this is a two major move, not much changed.
> Update qs to ^6

- package-lock.json
- package.json
Upgrades the `wpcom-xhr-request` to the recently released latest version that includes the `superagent` and `debug` upgrades.
Also updates the `package-lock.json` file with all the recent renovations by @blowery -- some only updated the `package.json` and not the lock.
> Upgrade wpcom-xhr-request to 1.1.2 and reshrinkwrap

- lib/me.js
- test/test.wpcom.me.js
- test/test.wpcom.site.js
This PR fixes the tests for the library, making them pass for (almost) any testing account.
**Remove the wpcom.me().groups() method**
The endpoint is available only to A12s and not interesting for public. The tests fail when testing with a non-A11n account.
**Fixup the wpcom.me().postsList() test**
Don't check for the `meta` field. It's present only if the posts list has multiple pages of results. Then there is a `meta.next_page` field with URL of the next page. For a testing account with a small number of posts, the `meta` field is not present and the test fails.
**Fixup the wpcom.site().statsComments() test**
For a site with small or zero number of comments, the `most_active_day` and `most_active_time` fields can be `null` rather than date/time strings. Fixup the test to check just …
> Remove the wpcom.me().groups() method and fixup tests

- lib/util/send-request.js
I've found a problem with declaring API version in the query argument. I'm using this lib from Calypso and in there, we are tracking what requests are currently being processed (stored in Redux). We identify those requests by a string token consisting of serialized site id and the query.
Example: I'm fetching posts of public post types from site 12345 and I need to override an API version. The serialized token for this request would be `12345:{"type":"public","apiVersion":"1.2"}`. 
Then I pass everything to wpcom.js to fetch me the data and it internally mutates the query argument (`delete query.apiVersion;`), so after successful/failed request when I try to get the serialized request token again to mark it as done, I would get `12345:{"type":"public"}` (no API version) and that wouldn't …
> Don't mutate query argument in sendRequest

- lib/util/request.js
For v1 wpcom endpoints, DELETE and PUT operations use http POST with a
special path, but v2 endpoints actually support all native http verbs.
Currently it's possible to override the verb using the `method` argument
in `Req.prototype.get` but not `put`, `post`, and `del`, which hard-code
the verb to POST.
While it would be nice if these methods automatically determined which
system to use, this is a good first step to allow all the methods to
accept the `method` argument and honor it in the same way.
> Allow overriding request http verb in post/put/del
